pipeline {
    agent any

    environment {
        VENV_PATH = "venv"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/manali-desai/aws_proj_final.git'
            }
        }

        stage('Setup Python Virtualenv') {
            steps {
                sh 'python3 -m venv ${VENV_PATH} || true'
                sh '. ${VENV_PATH}/bin/activate'
                sh 'pip install --upgrade pip'
                sh 'pip install -r flask_backend/requirements.txt'
            }
        }

        stage('Deploy Flask App') {
            steps {
                sh '''
                  . ${VENV_PATH}/bin/activate
                  pm2 delete flask-app || true
                  pm2 start ${VENV_PATH}/bin/python --name flask-app -- -m flask run --host=0.0.0.0 --port=8000
                '''
            }
        }
    }

    post {
        success {
            echo "Flask Pipeline Completed Successfully!"
        }
        failure {
            echo "Flask Pipeline Failed!"
        }
    }
}

