pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/manali-desai/aws_proj_final.git'
            }
        }

        stage('Create Python Virtualenv') {
            steps {
                sh '''
                  python3 -m venv venv
                  venv/bin/python3 -m pip install --upgrade pip
                  venv/bin/python3 -m pip install -r flask_backend/requirements.txt
                '''
            }
        }

        stage('Deploy Flask App') {
            steps {
                sh '''
                  venv/bin/python3 -m pip install pm2 || true
                  pm2 delete flask-app || true
                  pm2 start venv/bin/python --name flask-app -- -m flask run --host=0.0.0.0 --port=8000
                '''
            }
        }
    }

    post {
        success {
            echo "Flask Pipeline Completed Successfully!"
        }
        failure {
            echo "Flask Pipeline Failed!"
        }
    }
}

